# <font color='red'>Implement SGD Classifier with Logloss and L2 regularization Using SGD without using sklearn</font>

**There will be some functions that start with the word "grader" ex: grader_weights(), grader_sigmoid(), grader_logloss() etc, you should not change those function definition.<br><br>Every Grader function has to return True.**

<font color='red'> Importing packages</font>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model

<font color='red'>Creating custom dataset</font>

In [2]:
# please don't change random_state
X, y = make_classification(n_samples=50000, n_features=15, n_informative=10, n_redundant=5,
                           n_classes=2, weights=[0.7], class_sep=0.7, random_state=15)
# make_classification is used to create custom dataset 
# Please check this link (https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_classification.html) for more details

In [3]:
X.shape, y.shape

((50000, 15), (50000,))

In [4]:
np.unique(y, return_counts=True)

(array([0, 1]), array([34904, 15096], dtype=int64))

<font color='red'>Splitting data into train and test </font>

In [5]:
#please don't change random state
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=15)

In [6]:
# Standardizing the data.
scaler = StandardScaler()
x_train = scaler.fit_transform(X_train)
x_test = scaler.transform(X_test)

In [7]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((37500, 15), (37500,), (12500, 15), (12500,))

# <font color='red' size=5>SGD classifier</font>

In [8]:
# alpha : float
# Constant that multiplies the regularization term. 

# eta0 : double
# The initial learning rate for the ‘constant’, ‘invscaling’ or ‘adaptive’ schedules.

clf = linear_model.SGDClassifier(eta0=0.0001, alpha=0.0001, loss='log', random_state=15, penalty='l2', tol=1e-3, verbose=2, learning_rate='constant')
clf
# Please check this documentation (https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html) 

SGDClassifier(eta0=0.0001, learning_rate='constant', loss='log',
              random_state=15, verbose=2)

In [9]:
clf.fit(X=X_train, y=y_train) # fitting our model

-- Epoch 1
Norm: 0.77, NNZs: 15, Bias: -0.316653, T: 37500, Avg. loss: 0.455552
Total training time: 0.01 seconds.
-- Epoch 2
Norm: 0.91, NNZs: 15, Bias: -0.472747, T: 75000, Avg. loss: 0.394686
Total training time: 0.01 seconds.
-- Epoch 3
Norm: 0.98, NNZs: 15, Bias: -0.580082, T: 112500, Avg. loss: 0.385711
Total training time: 0.02 seconds.
-- Epoch 4
Norm: 1.02, NNZs: 15, Bias: -0.658292, T: 150000, Avg. loss: 0.382083
Total training time: 0.02 seconds.
-- Epoch 5
Norm: 1.04, NNZs: 15, Bias: -0.719528, T: 187500, Avg. loss: 0.380486
Total training time: 0.03 seconds.
-- Epoch 6
Norm: 1.05, NNZs: 15, Bias: -0.763409, T: 225000, Avg. loss: 0.379578
Total training time: 0.03 seconds.
-- Epoch 7
Norm: 1.06, NNZs: 15, Bias: -0.795106, T: 262500, Avg. loss: 0.379150
Total training time: 0.04 seconds.
-- Epoch 8
Norm: 1.06, NNZs: 15, Bias: -0.819925, T: 300000, Avg. loss: 0.378856
Total training time: 0.05 seconds.
-- Epoch 9
Norm: 1.07, NNZs: 15, Bias: -0.837805, T: 337500, Avg. loss: 0.

SGDClassifier(eta0=0.0001, learning_rate='constant', loss='log',
              random_state=15, verbose=2)

In [10]:
clf.coef_, clf.coef_.shape, clf.intercept_
#clf.coef_ will return the weights
#clf.coef_.shape will return the shape of weights
#clf.intercept_ will return the intercept term

(array([[-0.42336692,  0.18547565, -0.14859036,  0.34144407, -0.2081867 ,
          0.56016579, -0.45242483, -0.09408813,  0.2092732 ,  0.18084126,
          0.19705191,  0.00421916, -0.0796037 ,  0.33852802,  0.02266721]]),
 (1, 15),
 array([-0.8531383]))



```
# This is formatted as code
```

## <font color='red' size=5> Implement Logistic Regression with L2 regularization Using SGD: without using sklearn </font>






1.  We will be giving you some functions, please write code in that functions only.

2.  After every function, we will be giving you expected output, please make sure that you get that output. 






<br>

* Initialize the weight_vector and intercept term to zeros (Write your code in <font color='blue'>def initialize_weights()</font>)

* Create a loss function (Write your code in <font color='blue'>def logloss()</font>) 

 $log loss = -1*\frac{1}{n}\Sigma_{for each Yt,Y_{pred}}(Ytlog10(Y_{pred})+(1-Yt)log10(1-Y_{pred}))$
- for each epoch:

    - for each batch of data points in train: (keep batch size=1)

        - calculate the gradient of loss function w.r.t each weight in weight vector (write your code in <font color='blue'>def gradient_dw()</font>)

        $dw^{(t)} = x_n(y_n − σ((w^{(t)})^{T} x_n+b^{t}))- \frac{λ}{N}w^{(t)})$ <br>

        - Calculate the gradient of the intercept (write your code in <font color='blue'> def gradient_db()</font>) <a href='https://drive.google.com/file/d/1nQ08-XY4zvOLzRX-lGf8EYB5arb7-m1H/view?usp=sharing'>check this</a>

           $ db^{(t)} = y_n- σ((w^{(t)})^{T} x_n+b^{t}))$

        - Update weights and intercept (check the equation number 32 in the above mentioned <a href='https://drive.google.com/file/d/1nQ08-XY4zvOLzRX-lGf8EYB5arb7-m1H/view?usp=sharing'>pdf</a>): <br>
        $w^{(t+1)}← w^{(t)}+α(dw^{(t)}) $<br>

        $b^{(t+1)}←b^{(t)}+α(db^{(t)}) $
    - calculate the log loss for train and test with the updated weights (you can check the python assignment 10th question)
    - And if you wish, you can compare the previous loss and the current loss, if it is not updating, then
        you can stop the training
    - append this loss in the list ( this will be used to see how loss is changing for each epoch after the training is over )


<font color='blue'>Initialize weights </font>

In [11]:
X_train[0]

array([-0.57349184, -0.19015688, -0.06584143, -0.86990562, -2.80927706,
       -1.43345052,  0.35862361,  0.24627836, -2.25803168, -0.87761289,
        2.31023199, -0.3484947 , -2.2575668 , -1.93628665,  1.65242231])

In [12]:
def initialize_weights(dim):
    ''' In this function, we will initialize our weights and bias'''
    #initialize the weights to zeros array of (1,dim) dimensions
    #you use zeros_like function to initialize zero, check this link https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros_like.html
    #initialize bias to zero
    
    w = np.zeros_like(dim)
    b = 0 

    return w,b

In [13]:
dim = X_train[0] 
w,b = initialize_weights(dim)
print('w =',(w))
print('b =',str(b))

w = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
b = 0


In [14]:
w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<font color='cyan'>Grader function - 1 </font>

In [15]:
dim = X_train[0] 
w,b = initialize_weights(dim)
def grader_weights(w,b):
  assert ((len(w)==len(dim)) and b==0 and np.sum(w)==0.0)
  return True
grader_weights(w,b)

True

<font color='blue'>Compute sigmoid </font>

$sigmoid(z)= 1/(1+exp(-z))$

In [16]:
import math
def sigmoid(z):
    ''' In this function, we will return sigmoid of z'''
    # compute sigmoid(z) and return
    sigmoid_of_z = 1/(1 + (math.exp(-z)))
#     print(sigmoid_of_z)
    return sigmoid_of_z

<font color='cyan'>Grader function - 2</font>

In [17]:
def grader_sigmoid(z):
  val = sigmoid(z)
  assert(val==0.8807970779778823)
  return True
grader_sigmoid(2)

True

<font color='blue'> Compute loss </font>

$log loss = -1*\frac{1}{n}\Sigma_{for each Yt,Y_{pred}}(Ytlog10(Y_{pred})+(1-Yt)log10(1-Y_{pred}))$

In [18]:
import math

def logloss(y_true,y_pred):
    ''' In this function, we will compute log loss '''
    n = len(y_true)
    
    loss_sum1 = 0
    
    for i in range(len(y_true)):
        
        loss_s = (y_true[i]*(math.log10(y_pred[i])) + (1-y_true[i])*(math.log10(1-y_pred[i])))
        
        loss_sum1 = loss_sum1 + loss_s
        
    loss = -1*(1/n)*loss_sum1
    
#     print(loss)
    
    return loss


# true=[1,1,0,1,0]
# pred=[0,1,0,0,1]

# logloss(true,pred)

<font color='cyan'>Grader function - 3 </font>

In [19]:
def grader_logloss(true,pred):
  loss = logloss(true,pred)
  assert(loss == 0.07644900402910389)
  return True

true=[1,1,0,1,0]
pred=[0.9,0.8,0.1,0.8,0.2]

grader_logloss(true,pred)

True

<font color='blue'>Compute gradient w.r.to  'w' </font>

$dw^{(t)} = x_n(y_n − σ((w^{(t)})^{T} x_n+b^{t}))- \frac{λ}{N}w^{(t)}$ <br>

In [20]:
def gradient_dw (x,y,w,b,alpha,N) :
    '''In this function, we will compute the gardient w.r.to w '''
    
    z = np.sum(((w)*x)+b)
    
#     print(z)
    dw = (x * (y - sigmoid(z))) - (alpha/N)*w
#     print (dw)
    return dw

<font color='cyan'>Grader function - 4 </font>

In [21]:
def grader_dw(x,y,w,b,alpha,N):
  grad_dw = gradient_dw(x,y,w,b,alpha,N)
  assert(np.sum(grad_dw)==2.613689585)
  return True

grad_x = np.array([-2.07864835,  3.31604252, -0.79104357, -3.87045546, -1.14783286,
       -2.81434437, -0.86771071, -0.04073287,  0.84827878,  1.99451725,
        3.67152472,  0.01451875,  2.01062888,  0.07373904, -5.54586092])
grad_y = 0
grad_w,grad_b = initialize_weights(grad_x)
alpha=0.0001
N=len(X_train)
grader_dw(grad_x,grad_y,grad_w,grad_b,alpha,N)

True

<font color='blue'>Compute gradient w.r.to 'b' </font>

$ db^{(t)} = y_n- σ((w^{(t)})^{T} x_n+b^{t})$

In [22]:
def gradient_db(x,y,w,b):
    '''In this function, we will compute gradient w.r.to b '''
        
    z = np.sum((w*x) + b)

    db = y - sigmoid(z)
#     print(db)
    return db

<font color='cyan'>Grader function - 5 </font>

In [23]:
def grader_db(x,y,w,b):
  grad_db=gradient_db(x,y,w,b)
  assert(grad_db==-0.5)
  return True
grad_x=np.array([-2.07864835,  3.31604252, -0.79104357, -3.87045546, -1.14783286,
       -2.81434437, -0.86771071, -0.04073287,  0.84827878,  1.99451725,
        3.67152472,  0.01451875,  2.01062888,  0.07373904, -5.54586092])
grad_y=0
grad_w,grad_b=initialize_weights(grad_x)
alpha=0.0001
N=len(X_train)
grader_db(grad_x,grad_y,grad_w,grad_b)

True

<font color='blue'> Implementing logistic regression</font>

In [24]:
import numpy as np
epochs=50
l = np.zeros(epochs)
l

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
def train(X_train,y_train,X_test,y_test,epochs,alpha,eta0):
    ''' In this function, we will implement logistic regression'''
    
     
    N = len(X_train)


    return w_updated,b_updated,logloss_train,logloss_test

In [26]:
#Here eta0 is learning rate
    #implement the code as follows
    # initalize the weights (call the initialize_weights(X_train[0]) function)
    # for every epoch
        # for every data point(X_train,y_train)
           #compute gradient w.r.to w (call the gradient_dw() function)
           #compute gradient w.r.to b (call the gradient_db() function)
           #update w, b
            
        # predict the output of x_train[for all data points in X_train] using w,b
        # compute the loss between predicted and actual values (call the loss function)
        # store all the train loss values in a list
        
        # predict the output of x_test[for all data points in X_test] using w,b
        # compute the loss between predicted and actual values (call the loss function)
        # store all the test loss values in a list
        
        # you can also compare previous loss and current loss, if loss is not updating then stop the process and return w

In [27]:
N = len(X_train)
N

37500

In [34]:
def train(X_train,y_train,X_test,y_test,epochs,alpha,eta0):
    ''' In this function, we will implement logistic regression'''
    
     
    N = len(X_train)

    # initalize the weights (call the initialize_weights(X_train[0]) function)
    grad_w, grad_b = initialize_weights(X_train[0])
    w = grad_w
    b = grad_b

    logloss_train = np.zeros(epochs)
    logloss_test =  np.zeros(epochs)

    for i in range(50) :

    #  for every data point(X_train,y_train)
        for j in range(100) :

        #compute gradient w.r.to w (call the gradient_dw() function)
            grad_x = X_train[j]
            grad_y = y_train[j]

            x = grad_x
            y = grad_y

            grad_dw = gradient_dw(x,y,w,b,alpha,N)

            #           #compute gradient w.r.to b (call the gradient_db() function)
            grad_db = gradient_db(x,y,w,b)

            w_updated = w + (grad_dw*alpha)
            b_updated = b + (grad_db*alpha)

            def predict(w_updated,b_updated,X):
                N = len(X)
                predict = []
                for i in range(N):
                    z = np.dot(w.transpose(),X[i])+b
                    predict.append(sigmoid(z))
                #     print(predict)
                return np.array(predict)

            y_pred = predict(w_updated,b_updated,X_train)
            loss = logloss(y_train,y_pred)
            logloss_train[i] = loss

            y_pred = predict(w_updated,b_updated,X_test)
            loss = logloss(y_test,y_pred)
            logloss_test[i] = loss
            
    return w_updated,b_updated,logloss_train,logloss_test
    

In [ ]:
alpha=0.0001
eta0=0.0001
N=len(X_train)
epochs=50
w,b,train_loss_list,test_loss_list = train(X_train,y_train,X_test,y_test,epochs,alpha,eta0)
print("\n w_clf_coef = ",w)
print("\n b_clf_intercept = ",b)

print("\ntrain_loss_list =",train_loss_list )
print("\ntest_loss_list = ",test_loss_list )

In [ ]:
import matplotlib.pyplot as plt
plt.plot(list(range(len(train_loss_list))), train_loss_list , label=' Train loss')
plt.plot(list(range(len(test_loss_list))), test_loss_list , label=' Test loss')
plt.legend()
plt.xlabel("Epoch number")
plt.ylabel("Loss")

<font color='red'>Goal of assignment</font>

Compare your implementation and SGDClassifier's the weights and intercept, make sure they are as close as possible i.e difference should be in terms of 10^-3

In [ ]:
# these are the results we got after we implemented sgd and found the optimal weights and intercept
w-clf.coef_, b-clf.intercept_

<font color='blue'>Plot epoch number vs train , test loss </font>

* epoch number on X-axis
* loss on Y-axis

In [ ]:
def pred(w,b, X):
    N = len(X)
    predict = []
    for i in range(N):
        z=np.dot(w,X[i])+b
        if sigmoid(z) >= 0.5: # sigmoid(w,x,b) returns 1/(1+exp(-(dot(x,w)+b)))
            predict.append(1)
        else:
            predict.append(0)
#     print(predict)
    return np.array(predict)

print(1-np.sum(y_train - pred(w,b,X_train))/len(X_train))

print(1-np.sum(y_test  - pred(w,b,X_test))/len(X_test))